### ISSUE TITLE
Doubt about maximos input

### ISSUE THREAD

**Issue by amarcog** [aquimb/Autofocus-URJC#2]
Thank you for sharing these useful scripts. I was wondering which index format we have to input in maximos variable to properly select the best focused image within a stack. For example, in a Z-stack ranging from 1.tif to 20.tif, the image of the best focus is 10.tif. Should I input in maximos variable the id 10 or the id 9?. I am not sure is the script considers that python indexes are from 0 to 19.

**Comment by aquimb** [comment]
Hi Andrés!
Sorry for the delay. I assume you have already figured out, but just in case, the maximos variable considers 0 the first index, so in your example you should input the id 9.
Hope this is useful, and this project helps you on your work!

**Comment by amarcog** [comment]
Okay, thank you for the answer.
